"""connection list

Revision ID: 2fe83f155e69
Revises: 4dcff552e9e7
Create Date: 2026-06-06 00:05:41.479213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fe83f155e69'
down_revision = '4dcff552e9e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('connected_instagram_store_id_key', 'connected_instagram', type_='unique')
    op.drop_constraint('connected_pages_store_id_key', 'connected_pages', type_='unique')
    op.drop_constraint('connected_whatsapp_store_id_key', 'connected_whatsapp', type_='unique')

    op.drop_constraint('telegram_store_id_key', 'telegram', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('telegram_store_id_key', 'telegram', ['store_id'])

    op.create_unique_constraint('connected_whatsapp_store_id_key', 'connected_whatsapp', ['store_id'])
    op.create_unique_constraint('connected_pages_store_id_key', 'connected_pages', ['store_id'])
    op.create_unique_constraint('connected_instagram_store_id_key', 'connected_instagram', ['store_id'])
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name='langchain_pg_embedding_collection_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_embedding_pkey')
    )
    # ### end Alembic commands ###
