"""multi-tenant meta messaging

Revision ID: 0088bdf9432c
Revises: 2026_06_02_0001
Create Date: 2026-06-03 15:52:23.578076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0088bdf9432c'
down_revision = '2026_06_02_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_instagram',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('ig_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_user_id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('connected_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('connected_whatsapp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('waba_id', sa.String(length=255), nullable=False),
    sa.Column('phone_number_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.drop_table('messenger')
    op.drop_table('facebook_pages')
    op.drop_table('instagram')
    op.drop_table('whatsapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('phone_number_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('webhook_added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_status', postgresql.ENUM('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='whatsapp_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='whatsapp_pkey'),
    sa.UniqueConstraint('store_id', name='whatsapp_store_id_key')
    )
    op.create_table('instagram',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('instagram_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('webhook_added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_status', postgresql.ENUM('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='instagram_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='instagram_pkey'),
    sa.UniqueConstraint('store_id', name='instagram_store_id_key')
    )
    op.create_table('facebook_pages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('webhook_added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_status', postgresql.ENUM('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='facebook_pages_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='facebook_pages_pkey'),
    sa.UniqueConstraint('store_id', name='facebook_pages_store_id_key')
    )
    op.create_table('messenger',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('webhook_added_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('webhook_status', postgresql.ENUM('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='messenger_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messenger_pkey'),
    sa.UniqueConstraint('store_id', name='messenger_store_id_key')
    )
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('connected_whatsapp')
    op.drop_table('connected_pages')
    op.drop_table('connected_instagram')
    # ### end Alembic commands ###
