"""updated tables and names

Revision ID: 5408a48459d6
Revises: 93d5b26c1f18
Create Date: 2026-05-31 00:45:32.439771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5408a48459d6'
down_revision = '93d5b26c1f18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('products_items', sa.JSON(), nullable=False),
        sa.Column('tone', sa.String(length=100), nullable=True),
        sa.Column('personality_prompt', sa.Text(), nullable=True),
        sa.Column('welcome_message', sa.Text(), nullable=True),
        sa.Column('language', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('store_id', sa.UUID(), nullable=False),
        sa.Column('filename', sa.String(length=500), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('PROCESSING', 'INDEXED', 'FAILED', name='documentstatus'), nullable=False),
        sa.Column('chunk_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('businesses')
    op.add_column('facebook_pages', sa.Column('store_id', sa.UUID(), nullable=False))
    op.drop_constraint('facebook_pages_business_id_key', 'facebook_pages', type_='unique')
    op.create_unique_constraint(None, 'facebook_pages', ['store_id'])
    op.drop_constraint('facebook_pages_business_id_fkey', 'facebook_pages', type_='foreignkey')
    op.create_foreign_key(None, 'facebook_pages', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('facebook_pages', 'business_id')
    op.add_column('instagram', sa.Column('store_id', sa.UUID(), nullable=False))
    op.drop_constraint('instagram_business_id_key', 'instagram', type_='unique')
    op.create_unique_constraint(None, 'instagram', ['store_id'])
    op.drop_constraint('instagram_business_id_fkey', 'instagram', type_='foreignkey')
    op.create_foreign_key(None, 'instagram', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('instagram', 'business_id')
    op.add_column('messenger', sa.Column('store_id', sa.UUID(), nullable=False))
    op.drop_constraint('messenger_business_id_key', 'messenger', type_='unique')
    op.create_unique_constraint(None, 'messenger', ['store_id'])
    op.drop_constraint('messenger_business_id_fkey', 'messenger', type_='foreignkey')
    op.create_foreign_key(None, 'messenger', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messenger', 'business_id')
    op.add_column('telegram', sa.Column('store_id', sa.UUID(), nullable=False))
    op.drop_constraint('telegram_business_id_key', 'telegram', type_='unique')
    op.create_unique_constraint(None, 'telegram', ['store_id'])
    op.drop_constraint('telegram_business_id_fkey', 'telegram', type_='foreignkey')
    op.create_foreign_key(None, 'telegram', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('telegram', 'business_id')
    op.add_column('whatsapp', sa.Column('store_id', sa.UUID(), nullable=False))
    op.drop_constraint('whatsapp_business_id_key', 'whatsapp', type_='unique')
    op.create_unique_constraint(None, 'whatsapp', ['store_id'])
    op.drop_constraint('whatsapp_business_id_fkey', 'whatsapp', type_='foreignkey')
    op.create_foreign_key(None, 'whatsapp', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('whatsapp', 'business_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'whatsapp', type_='foreignkey')
    op.create_foreign_key('whatsapp_business_id_fkey', 'whatsapp', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'whatsapp', type_='unique')
    op.create_unique_constraint('whatsapp_business_id_key', 'whatsapp', ['business_id'])
    op.drop_column('whatsapp', 'store_id')
    op.add_column('telegram', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'telegram', type_='foreignkey')
    op.create_foreign_key('telegram_business_id_fkey', 'telegram', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'telegram', type_='unique')
    op.create_unique_constraint('telegram_business_id_key', 'telegram', ['business_id'])
    op.drop_column('telegram', 'store_id')
    op.add_column('messenger', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messenger', type_='foreignkey')
    op.create_foreign_key('messenger_business_id_fkey', 'messenger', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messenger', type_='unique')
    op.create_unique_constraint('messenger_business_id_key', 'messenger', ['business_id'])
    op.drop_column('messenger', 'store_id')
    op.add_column('instagram', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'instagram', type_='foreignkey')
    op.create_foreign_key('instagram_business_id_fkey', 'instagram', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'instagram', type_='unique')
    op.create_unique_constraint('instagram_business_id_key', 'instagram', ['business_id'])
    op.drop_column('instagram', 'store_id')
    op.add_column('facebook_pages', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'facebook_pages', type_='foreignkey')
    op.create_foreign_key('facebook_pages_business_id_fkey', 'facebook_pages', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'facebook_pages', type_='unique')
    op.create_unique_constraint('facebook_pages_business_id_key', 'facebook_pages', ['business_id'])
    op.drop_column('facebook_pages', 'store_id')
    op.create_table('businesses',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('products_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='businesses_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='businesses_pkey')
    )
    op.drop_table('store_documents')
    op.drop_table('stores')
    # ### end Alembic commands ###
