"""page name

Revision ID: 4dcff552e9e7
Revises: d6g7h8i9j0k1
Create Date: 2026-06-05 23:53:34.177277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dcff552e9e7'
down_revision = 'd6g7h8i9j0k1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_instagram', sa.Column('ig_username', sa.String(length=255), nullable=True))
    op.add_column('connected_pages', sa.Column('page_name', sa.String(length=255), nullable=True))
    op.add_column('connected_whatsapp', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_whatsapp', 'name')
    op.drop_column('connected_pages', 'page_name')
    op.drop_column('connected_instagram', 'ig_username')
    # ### end Alembic commands ###
