"""initial models added

Revision ID: 93d5b26c1f18
Revises: 
Create Date: 2026-01-05 17:38:20.434134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d5b26c1f18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('products_items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('webhook_added_date', sa.DateTime(), nullable=True),
    sa.Column('webhook_status', sa.Enum('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('instagram',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('webhook_added_date', sa.DateTime(), nullable=True),
    sa.Column('webhook_status', sa.Enum('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('messenger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('page_id', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('webhook_added_date', sa.DateTime(), nullable=True),
    sa.Column('webhook_status', sa.Enum('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('telegram',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('bot_token', sa.String(length=500), nullable=False),
    sa.Column('bot_username', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('webhook_added_date', sa.DateTime(), nullable=True),
    sa.Column('webhook_status', sa.Enum('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('whatsapp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('business_account_id', sa.String(length=255), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('webhook_added_date', sa.DateTime(), nullable=True),
    sa.Column('webhook_status', sa.Enum('VERIFIED', 'PENDING', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('status', sa.Enum('PAUSED', 'ACTIVE', 'INACTIVE', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp')
    op.drop_table('telegram')
    op.drop_table('messenger')
    op.drop_table('instagram')
    op.drop_table('facebook_pages')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
