"""Add token to whatsapp and instagram

Revision ID: 833641117afe
Revises: 0088bdf9432c
Create Date: 2026-06-03 15:53:52.751382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833641117afe'
down_revision = '0088bdf9432c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_instagram', sa.Column('token', sa.String(length=500), nullable=True))
    op.add_column('connected_whatsapp', sa.Column('token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_whatsapp', 'token')
    op.drop_column('connected_instagram', 'token')
    # ### end Alembic commands ###
