"""Capitalize enums

Revision ID: 6289d864192c
Revises: 2fe83f155e69
Create Date: 2026-06-06 02:05:50.227962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6289d864192c'
down_revision = '2fe83f155e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename posttype enum values
    op.execute("ALTER TYPE posttype RENAME VALUE 'product' TO 'PRODUCT'")
    op.execute("ALTER TYPE posttype RENAME VALUE 'meme' TO 'MEME'")
    op.execute("ALTER TYPE posttype RENAME VALUE 'quote' TO 'QUOTE'")
    
    # Rename postsource enum values
    op.execute("ALTER TYPE postsource RENAME VALUE 'webhook' TO 'WEBHOOK'")
    op.execute("ALTER TYPE postsource RENAME VALUE 'generated' TO 'GENERATED'")
    
    # Rename responselanguage enum values
    # DB shows they might already be uppercase, so we use IF EXISTS or catch it if we could,
    # but ALTER TYPE RENAME VALUE doesn't support IF EXISTS easily. Let's just execute for posttype
    # since responselanguage is already ADAPTIVE, BANGLA, ENGLISH according to DB.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE posttype RENAME VALUE 'PRODUCT' TO 'product'")
    op.execute("ALTER TYPE posttype RENAME VALUE 'MEME' TO 'meme'")
    op.execute("ALTER TYPE posttype RENAME VALUE 'QUOTE' TO 'quote'")

    op.execute("ALTER TYPE postsource RENAME VALUE 'WEBHOOK' TO 'webhook'")
    op.execute("ALTER TYPE postsource RENAME VALUE 'GENERATED' TO 'generated'")
    # ### end Alembic commands ###
